# -*- coding: utf-8 -*-
"""task3_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fthSLMBU2yjaVHxzB9h5tnDjBygFaNuy
"""

import pandas as pd
import numpy as np
# Load the dataset
df = pd.read_csv("/content/trends_clean.csv")

# print first 5 rows
print("First 5 rows")
print(df.head())

# print shape of Dataframe
print("Shape of Dataframe")
print(df.shape)

import pandas as pd
df = pd.read_csv("/content/trends_clean.csv")

avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()
print("Average score :",avg_score)
print("Average comments :",avg_comments)

"""###2 — Basic Analysis with NumPy"""

print("\n--- NumPy Stats ---")
print("Mean score :",np.mean(df["score"]))
print("median score: ",np.median(df["score"]))
print("standard deviation",np.std(df["score"]))
print("Highest score :",np.max(df["score"]))
print("Lowest score :",np.min(df["score"]))

# Category with most stories
print("Category with most stories :",df["category"].value_counts().idxmax())

# Story with most comments
print("Story with most comments :",df.loc[df["num_comments"].idxmax()]["title"])

"""###3 — Add New Columns"""

# Engagement column
avg_score = df["score"].mean()
df["engagement"] = df["num_comments"]/(df["score"] + 1)
# is_popular column
df["is_popular"] = df["score"] > avg_score
# preview result
print(df.head())

"""###4 — Save the Result"""

import os
os.makedirs("data", exist_ok=True)

output_path = "data/trends_analysed.csv"
df.to_csv(output_path, index=False)

print(f"File saved successfully at {output_path}")