# -*- coding: utf-8 -*-
"""task1_data_collection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLnMeFfIsGHoIEVa6mkvz6L0jZvX7R8v
"""

# -*- coding: utf-8 -*-
"""task1_data_collection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouXDWwBL-DTBNUWGZ9SVyneTE4njfnSS

####Task 1 — Fetch Data from API
"""

import requests
import time as tm
# Dictionary that maps categories to related keywords
# These keywords will be used to classify story titles
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"],
}
# Custom header to avoid request blocking
headers = {"User-Agent": "TrendPulse/1.0"}
# API endpoints
top_story_IDs = "https://hacker-news.firebaseio.com/v0/topstories.json"
item_url = "https://hacker-news.firebaseio.com/v0/item/{id}.json"


# ── Step 1: Get the list of top story IDs ──────────────────────────
def get_top_story_ids():
    try:
        response = requests.get(top_story_IDs, headers=headers, timeout=5)
        response.raise_for_status()
        ids = response.json()
        return ids[:100]          # fetch the first 20 as instructed
    except requests.RequestException as e:
        print(f"Failed to fetch story IDs: {e}")
        return []

# ── Step 2: Get each story's details ──────────────────────────────
def get_story_details(story_id):

    try:
      response = requests.get(item_url.format(id=story_id), headers=headers, timeout=5)
      response.raise_for_status()
      story = response.json()
      return story
    except requests.RequestException as e:
      print(f"Failed to fetch story details for ID {story_id}: {e}")
      return None

# ── Step 3: Categorize stories by title keywords ──────────────────
def categorise_by_story(title):
    title = title.lower()
    for category, keywords in CATEGORIES.items():
        if any(keyword.lower() in title for keyword in keywords):
            return category
    return "other" # Default category if no keywords match


def main():
    print("Fetching top story IDs...")
    top_story_ids = get_top_story_ids()
    print(f"Fetched {len(top_story_ids)} IDs. Fetching details...\n")


    # Fetch all story details first
    all_stories = []
    for story_id in top_story_ids:
      story = get_story_details(story_id)
      if story:
        all_stories.append(story)

    # Group stories into categories
    categorized_stories = {}
    for story in all_stories:
      title = story.get("title", "")
      category = categorise_by_story(title)
      if category not in categorized_stories:
        categorized_stories[category] = []
      categorized_stories[category].append(title)


    # Print results with delay
    print("Top Stories by Category:")
    for category, titles in categorized_stories.items():
        print(f"\nCategory: {category}")
        print(f"Total: {len(titles)}")
        # Print only the first 3 titles for brevity
        for t in titles[:3]:
            print(f"- {t}")
        tm.sleep(2) # Wait 2 seconds between each category


if __name__ == "__main__":
    main()

"""###2 — Extract the Fields"""

import requests
from datetime import datetime
import json
import os

# API base URL
BASE_URL = "https://hacker-news.firebaseio.com/v0"

# Simple category function (you already used this logic)
def categorize(title):
    if not title:
        return "uncategorized"

    title_lower = title.lower()

    # Technology
    if any(word in title_lower for word in [
        "ai", "llm", "tech", "software", "code", "computer",
        "data", "cloud", "api", "gpu", "iphone", "youtube", "copilot"
    ]):
        return "technology"

    # Sports
    elif any(word in title_lower for word in [
        "game", "player", "team", "match", "league", "football", "cricket"
    ]):
        return "sports"

    # Science
    elif any(word in title_lower for word in [
        "research", "study", "space", "physics", "biology", "nasa"
    ]):
        return "science"

    # Entertainment
    elif any(word in title_lower for word in [
        "movie", "film", "music", "show", "netflix", "series"
    ]):
        return "entertainment"

    # World News
    elif any(word in title_lower for word in [
        "government", "war", "election", "country", "president"
    ]):
        return "worldnews"

    return "uncategorized"

# Extract required fields
def extract_fields(story):
    return {
        "post_id": story.get("id"),
        "title": story.get("title", ""),
        "category": categorize(story.get("title", "")),
        "score": story.get("score", 0),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by", ""),
        "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }


# Get top story IDs
def get_top_story_ids():
    response = requests.get(f"{BASE_URL}/topstories.json")
    return response.json()[:122]   # keep small for fast run


# Get story details
def get_story_details(story_id):
    try:
        response = requests.get(f"{BASE_URL}/item/{story_id}.json")
        return response.json()
    except:
        print(f"Skipping story {story_id}")
        return None


# Main
def main():
    ids = get_top_story_ids()

    extracted_stories = []

    for sid in ids:
        story = get_story_details(sid)

        if story and "title" in story:
            cleaned = extract_fields(story)
            extracted_stories.append(cleaned)

    # Create data directory if it doesn't exist
    data_dir = "data/"
    os.makedirs(data_dir, exist_ok=True)

    # Generate filename with current date
    current_date = datetime.now().strftime("%Y%m%d")
    filename = os.path.join(data_dir, f"trends_{current_date}.json")

    # Save stories to JSON file
    with open(filename, "w") as f:
        json.dump(extracted_stories, f, indent=4)

    print(f"\nCollected {len(extracted_stories)} stories. Saved to {filename}")

    # Print sample output
    print("\nExtracted Stories (first 7 for sample):\n")
    for s in extracted_stories[:7]:
        print(s)


if __name__ == "__main__":
    main()