# -*- coding: utf-8 -*-
"""task4_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfKrLIDly6Zhjo6twi2oafyXmZ7a_1dS

####Task 4 — Visualizations
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
df= pd.read_csv("/content/trends_analysed.csv")
df

# Create "output" folder if it doesn't exist
os.makedirs("output", exist_ok=True)
print("outputs/folder is ready")
plt.show()

"""###Chart 1: Top 10 Stories by Score"""

# create a horizontal bar chart showing the top 10 stories by score
# Step 2: Chart 1 - Top 10 Stories by Score
top10 = df.sort_values(by="score", ascending=False).head(10)
# Shorten titles longer than 50 characters
top10["short_title"] = top10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

# Create horizontal bar chart
plt.figure()

plt.barh(top10["short_title"], top10["score"])

# Labels and title
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")

# Highest score on top
plt.gca().invert_yaxis()

# Adjust layout and save
plt.tight_layout()
plt.savefig("output/chart1_top_stories.png")

# Show chart
plt.show()

"""####Chart 2: Stories per Category"""

# Count stories per category
category_counts = df["category"].value_counts()

# Create bar chart
plt.figure()

plt.bar(category_counts.index, category_counts.values,
        color=["red","green","yellow","blue","orange"])

# Labels and title
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Number of Stories per Category")

# Rotate x-axis labels (if long)
plt.xticks(rotation=45)

# Adjust layout and save
plt.tight_layout()
plt.savefig("output/chart2_categories.png", dpi=300)

# Show chart
plt.show()

"""###Chart 3: Score vs Comments"""

# Ensure is_popular column exists
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score

# Split data
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

# Create scatter plot
plt.figure()

plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

# Labels and title
plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Number of Comments")

# Legend
plt.legend()

# Save BEFORE show
plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png", dpi=300)

# Show plot
plt.show()

# Ensure is_popular column exists
avg_score = df["score"].mean()
df["is_popular"] = df["score"] > avg_score

# Split data
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

# Create scatter plot
plt.figure()

plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

# Labels and title
plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Number of Comments")

# Legend
plt.legend()

# Save BEFORE show
plt.tight_layout()
plt.savefig("output/chart3_scatter.png", dpi=300)

# Show plot
plt.show()

# Prepare data
top10 = df.sort_values(by="score", ascending=False).head(10).copy()
top10["short_title"] = top10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

category_counts = df["category"].value_counts()

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

# Create subplots (1 row, 3 columns)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 🔹 Chart 1: Top 10 Stories
axes[0].barh(top10["short_title"], top10["score"])
axes[0].set_title("Top 10 Stories")
axes[0].set_xlabel("Score")
axes[0].invert_yaxis()

# 🔹 Chart 2: Categories
axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Stories per Category")
axes[1].set_xlabel("Category")
axes[1].set_ylabel("Count")
axes[1].tick_params(axis='x', rotation=45)

# 🔹 Chart 3: Scatter
axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].set_xlabel("Score")
axes[2].set_ylabel("Comments")
axes[2].legend()

# Overall title
plt.suptitle("TrendPulse Dashboard")

# Adjust layout and save
plt.tight_layout()
plt.savefig("output/dashboard.png", dpi=300)

# Show
plt.show()

import os
print(os.listdir("output"))