# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouXDWwBL-DTBNUWGZ9SVyneTE4njfnSS

####Task 2 — Clean the Data & Save as CSV
"""

# Load the JSON File
import pandas as pd
df = pd.read_json("/content/trends_20260406.json")
print(f"Rows loaded: {len(df)}")

# Clean the Data
# Duplicates- remove rows with the same post_id
df= df.drop_duplicates(subset=['post_id'])
df

# missing value- drop rows where post_id,title,or score is misssing
df = df.dropna(subset=['post_id','title','score'])
df

# Data types
# Data types — make sure score and num_comments are integers
df['score'] = df['score'].astype(int)
df['num_comments'] = df['num_comments'].astype(int)
df.dtypes

# remove stories where score is less than 5
df = df[df['score'] >= 5]
df

# Whitespace — strip extra spaces from the title column
df["title"] = df["title"].str.strip()

print(f"Rows after cleaning: {len(df)}")

print("Loaded", len(df), "stories")
print("After removing duplicates:", len(df))
print("After removing nulls:", len(df))
print("After removing low scores:", len(df))

"""###3 — Save as CSV"""

import os

# Make sure the data/ folder exists
os.makedirs("data", exist_ok=True)

output_path = "data/trends_clean.csv"
df.to_csv(output_path, index=False)

print(f"Saved {len(df)} rows to {output_path}")

# Quick summary: stories per category
print("\nStories per category:")
print(df["category"].value_counts().to_string())